### ISSUE TITLE
AttributeError: module 'torch' has no attribute 'autocast'

### ISSUE THREAD

**Issue by ndmm-zwm** [va1shn9v/PromptIR#19]
When I want to try to test the code, I encountered the following problem, how should I solve it?
Here's the error.
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    import lightning.pytorch as pl
  File "/home/isalab102/anaconda3/envs/promptir/lib/python3.8/site-packages/lightning/__init__.py", line 25, in <module>
    from lightning.fabric.fabric import Fabric  # noqa: E402
  File "/home/isalab102/anaconda3/envs/promptir/lib/python3.8/site-packages/lightning/fabric/__init__.py", line 29, in <module>
    from lightning.fabric.fabric import Fabric  # noqa: E402
  File "/home/isalab102/anaconda3/envs/promptir/lib/python3.8/site-packages/lightning/fabric/fabric.py", line 32, in <module>
    from lightning.fabric.plugins import Precision  # avoid circular imports: # isort: split
  File "/home/isalab102/anaconda3/envs/promptir/lib/python3.8/site-packages/lightning/fabric/plugins/__init__.py", line 18, in <module>
    from lightning.fabric.plugins.precision.amp import MixedPrecision
  File "/home/isalab102/anaconda3/envs/promptir/lib/python3.8/site-packages/lightning/fabric/plugins/precision/__init__.py", line 14, in <module>
    from lightning.fabric.plugins.precision.amp import MixedPrecision
  File "/home/isalab102/anaconda3/envs/promptir/lib/python3.8/site-packages/lightning/fabric/plugins/precision/amp.py", line 29, in <module>
    class MixedPrecision(Precision):
  File "/home/isalab102/anaconda3/envs/promptir/lib/python3.8/site-packages/lightning/fabric/plugins/precision/amp.py", line 96, in MixedPrecision
    def _autocast_context_manager(self) -> torch.autocast:
AttributeError: module 'torch' has no attribute 'autocast'

**Comment by Xiaozhoushen** [comment]
I have encountered the same issue. Have you resolved it?
