### ISSUE TITLE
Error with Demo

### ISSUE THREAD

**Issue by munib94** [va1shn9v/PromptIR#32]
Hi

I am having issues when I try to execute the following:

`python demo.py --test_path './test/demo/image.png' --output_path './output/demo/'`

My error is:

```
Traceback (most recent call last):
  File "demo.py", line 108, in <module>
    net  = PromptIRModel().load_from_checkpoint(ckpt_path).to(device)
  File "/home/user/.pyenv/versions/promptir/lib/python3.8/site-packages/lightning/pytorch/utilities/model_helpers.py", line 121, in wrapper
    raise TypeError(
TypeError: The classmethod `PromptIRModel.load_from_checkpoint` cannot be called on an instance. Please call it on the class type and make sure the return value is used.
```

I did not make any modifications to the code. Help with this issue is much appreciated.

**Comment by munib94** [comment]
Nevermind, I downgraded my lightning package to match the version in the env.yml file. This solved the issue.
